services:
  #
  # Main services
  #
  backend:
    command: "/app/scripts/backend.sh"
    tty: true
    stdin_open: true
    container_name: "weatherapp_backend"
    user: "web:web"
    build:
      context: .
      target: weatherapp_backend
    volumes:
     - ".:/app/"
    environment:
      - NODE_DEBUG
      - DEBUG
      - PORT=9000
      - APPID
      - MAP_ENDPOINT
    ports:
     - "9000:9000"

  frontend:
    command: "/app/scripts/frontend.sh"
    tty: true
    stdin_open: true
    container_name: "weatherapp_frontend"
    user: "web:web"
    build:
      context: .
      target: weatherapp_frontend
    volumes:
     - ".:/app/"
    environment:
      - NODE_DEBUG
      - DEBUG
      - PORT=8000
      - NODE_ENV
#      - ENDPOINT='http://localhost:9000/api'
    ports:
     - "8000:8000"
    links:
     - backend

  nginx:
    image: nginx:latest
    container_name: weatherapp_nginx
    tty: true
    stdin_open: true
    command: /bin/bash -c "cat /etc/nginx/conf.d/templates/*.conf.template|envsubst '$$PRODUCTION_PORT' > /etc/nginx/conf.d/default.conf && cat /etc/nginx/conf.d/*.conf && nginx -g 'daemon off;'"
    volumes:
      - ./:/app
      - ./nginx/:/etc/nginx/conf.d/templates
    # TODO: use env vars here
    ports:
      - 80:80
    environment:
      - PRODUCTION_PORT=80
    links:
      - backend

  testing:
    command: "/app/scripts/test.sh"
    tty: true
    stdin_open: true
    container_name: "weatherapp_testing"
    user: "web:web"
    build:
      context: .
      target: weatherapp_testing
    volumes:
     - ".:/app/"
    environment:
      - NODE_DEBUG
      - MAP_ENDPOINT=http://mockapi:9100/data/2.5
      - STAY_ALIVE
    links:
     - mockapi

  mockapi:
    command: "/app/scripts/mockapi.sh"
    tty: true
    stdin_open: true
    container_name: "weatherapp_mockapi"
    user: "web:web"
    build:
      context: .
      target: weatherapp_mockapi
    volumes:
     - ".:/app/"
    environment:
      - NODE_DEBUG
      - PORT=9100
    ports:
     - "9100:9100"